// ============================================================================
// MEDIDAS HTML — Organizadas por página del dashboard
// ----------------------------------------------------------------------------
// Tabla destino:  06_medidas_html
// Visual requerido en Power BI: "HTML Content" (custom visual de Daniel
// Marsh-Patrick disponible en AppSource). Cualquier visual que renderice
// HTML inline funciona.
//
// Las medidas devuelven strings HTML completos con estilos inline aplicando
// la paleta Bilbao Analytics (#0D0D1A, #1A1A2E, #00D4FF, #7B2FBE, #00E396,
// #FFB020, #FF4D6D, #9090A8, #E8E8F0).
//
// TIPOS DE COMPONENTES:
//   · KPI Cards: tarjetas con número grande + variación
//   · Banners: cintas narrativas coloreadas
//   · Narrativa: párrafos dinámicos
//   · Tablas: HTML tables con paleta de marca
//   · Charts SVG: sparklines, boxplots, líneas de forecast, bars comparativos
//
// Organización por carpeta (cada carpeta = una página del dashboard):
//   P1 · Resumen Ejecutivo    → 9 medidas (incluye sparkline)
//   P2 · Análisis de Skills   → 6 medidas
//   P3 · Inteligencia Salarial → 9 medidas (incluye 2 boxplots)
//   P4 · Mapa Geográfico      → 5 medidas
//   P5 · Predicciones Prophet → 7 medidas (incluye línea con banda)
//   P6 · Perfiles Clusters    → 6 medidas (incluye bars comparativo)
//                              TOTAL: 42 medidas HTML
// ============================================================================


// ════════════════════════════════════════════════════════════════════════════
//  P1 · RESUMEN EJECUTIVO
// ════════════════════════════════════════════════════════════════════════════

HTML P1 · Titulo =
"<div style='font-family:Segoe UI,Arial,sans-serif;padding:8px 0;'>"
& "<div style='color:#00D4FF;font-size:24px;font-weight:300;'>🌌 Observatorio del Mercado Laboral</div>"
& "<div style='color:#9090A8;font-size:13px;margin-top:4px;'>Resumen Ejecutivo · Bilbao Analytics</div>"
& "</div>"


HTML P1 · KPI Total Ofertas =
VAR _Total = [Total Ofertas]
VAR _Var   = [Var MoM Ofertas]
VAR _Color = IF ( NOT ISBLANK ( _Var ) && _Var >= 0, "#00E396", "#FF4D6D" )
VAR _Arrow = IF ( NOT ISBLANK ( _Var ) && _Var >= 0, "▲", "▼" )
VAR _VarText = IF ( ISBLANK ( _Var ), "—", _Arrow & " " & FORMAT ( _Var, "0.0%" ) & " MoM" )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #00D4FF;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>📊 Total Ofertas</div>"
        & "<div style='color:#00D4FF;font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>" & FORMAT ( _Total, "#,##0" ) & "</div>"
        & "<div style='color:" & _Color & ";font-size:13px;font-weight:600;margin-top:8px;'>" & _VarText & "</div>"
    & "</div>"


HTML P1 · KPI Salario Mediano =
VAR _Med = [Salario Mediano USD]
VAR _P10 = [Salario P10 USD]
VAR _P90 = [Salario P90 USD]
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #7B2FBE;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>💰 Salario Mediano</div>"
        & "<div style='color:#7B2FBE;font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>$" & FORMAT ( DIVIDE ( _Med, 1000 ), "0.0" ) & "K</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>p10-p90: $" & FORMAT ( DIVIDE ( _P10, 1000 ), "0" ) & "K - $" & FORMAT ( DIVIDE ( _P90, 1000 ), "0" ) & "K</div>"
    & "</div>"


HTML P1 · KPI Pct Remoto =
VAR _R = [Pct Remoto]
VAR _H = [Pct Hibrido]
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #00E396;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>🌐 Trabajo Remoto</div>"
        & "<div style='color:#00E396;font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>" & FORMAT ( _R, "0.0%" ) & "</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>+ " & FORMAT ( _H, "0.0%" ) & " hibrido</div>"
    & "</div>"


HTML P1 · KPI Top Skill =
VAR _T = [Top Skill del Mes]
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #FFB020;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>🏆 Top Skill del Periodo</div>"
        & "<div style='color:#FFB020;font-size:28px;font-weight:300;line-height:1.1;margin-top:8px;'>" & IF ( ISBLANK ( _T ), "—", _T ) & "</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>Skill mas mencionada</div>"
    & "</div>"


HTML P1 · KPI Skills en Alerta =
VAR _C     = [Skills en Alerta] + 0
VAR _Color = IF ( _C > 0, "#FF4D6D", "#9090A8" )
VAR _Icono = IF ( _C > 0, "🚨", "✅" )
VAR _T     = IF ( _C > 0, "Skills con cambio >=30% MoM", "Sin alertas - mercado estable" )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid " & _Color & ";'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>" & _Icono & " Alertas Activas</div>"
        & "<div style='color:" & _Color & ";font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>" & FORMAT ( _C, "#,##0" ) & "</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>" & _T & "</div>"
    & "</div>"


HTML P1 · Banner Estado Periodo =
VAR _A = [Skills en Alerta] + 0
VAR _Color = SWITCH ( TRUE (), _A >= 3, "#FF4D6D", _A > 0, "#FFB020", "#00E396" )
VAR _T = SWITCH (
    TRUE (),
    _A >= 3, "🚨 Mercado en movimiento intenso - " & _A & " skills con cambios criticos detectados",
    _A >  0, "⚡ Atencion - " & _A & " skill(s) con cambios notables",
    "✅ Mercado estable - sin cambios significativos"
)
RETURN
    "<div style='background:#1A1A2E;border:1px solid " & _Color & ";border-left:4px solid " & _Color & ";border-radius:6px;padding:14px 20px;font-family:Segoe UI,Arial,sans-serif;color:" & _Color & ";font-size:14px;font-weight:600;'>"
    & _T
    & "</div>"


HTML P1 · Narrativa Resumen =
VAR _Total = [Total Ofertas]
VAR _Var   = [Var MoM Ofertas]
VAR _Sal   = [Salario Mediano USD]
VAR _Rem   = [Pct Remoto]
VAR _Top   = [Top Skill del Mes]
VAR _VL    = IF ( _Var >= 0, "crecio", "decrecio" )
VAR _AV    = ABS ( _Var )
VAR _VC    = IF ( _Var >= 0, "#00E396", "#FF4D6D" )
RETURN
    "<div style='background:#1A1A2E;padding:24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;line-height:1.6;font-size:14px;'>"
        & "<div style='color:#00D4FF;font-size:16px;font-weight:600;margin-bottom:12px;'>📋 Resumen del periodo</div>"
        & "El mercado registro <b style='color:#00D4FF;'>" & FORMAT ( _Total, "#,##0" ) & " ofertas</b>"
        & IF ( ISBLANK ( _Var ), "", ", con una variacion que <b style='color:" & _VC & ";'>" & _VL & " un " & FORMAT ( _AV, "0.0%" ) & "</b> respecto al mes anterior" )
        & ". El salario mediano se ubica en <b style='color:#7B2FBE;'>$" & FORMAT ( DIVIDE ( _Sal, 1000 ), "0.0" ) & "K USD</b>, "
        & "con <b style='color:#00E396;'>" & FORMAT ( _Rem, "0.0%" ) & " de ofertas remotas</b>. "
        & IF ( ISBLANK ( _Top ), "", "Skill destacada: <b style='color:#FFB020;'>" & _Top & "</b>." )
    & "</div>"


HTML P1 · Sparkline Tendencia =
// SVG sparkline con la tendencia mensual de ofertas en los meses con datos.
// Calcula el delta absoluto entre el primer y último mes para mostrar
// variación global del periodo.
VAR _Data =
    ADDCOLUMNS (
        FILTER ( VALUES ( Dim_Calendario[InicioMes] ), CALCULATE ( [Total Ofertas] ) > 0 ),
        "N", CALCULATE ( [Total Ofertas] )
    )
VAR _Sorted = ADDCOLUMNS ( _Data, "Idx", RANKX ( _Data, Dim_Calendario[InicioMes], , ASC, DENSE ) )
VAR _Max    = MAXX ( _Sorted, [N] ) + 0.0001
VAR _Min    = MINX ( _Sorted, [N] )
VAR _Range  = _Max - _Min + 0.0001
VAR _N      = COUNTROWS ( _Sorted ) + 0
VAR _Width  = 280
VAR _Height = 70
VAR _StepX  = DIVIDE ( _Width - 10, _N - 1 )
VAR _Points =
    CONCATENATEX (
        _Sorted,
        FORMAT ( 5 + ( [Idx] - 1 ) * _StepX, "0" ) & "," &
        FORMAT ( _Height - 5 - DIVIDE ( [N] - _Min, _Range ) * ( _Height - 15 ), "0" ),
        " ",
        [Idx], ASC
    )
VAR _LastN  = MAXX ( TOPN ( 1, _Sorted, [Idx], DESC ), [N] )
VAR _FirstN = MAXX ( TOPN ( 1, _Sorted, [Idx], ASC ),  [N] )
VAR _Delta      = DIVIDE ( _LastN - _FirstN, _FirstN )
VAR _DeltaColor = IF ( _Delta >= 0, "#00E396", "#FF4D6D" )
VAR _DeltaIcon  = IF ( _Delta >= 0, "▲", "▼" )
RETURN
    "<div style='background:#1A1A2E;padding:16px 20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;'>"
        & "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;'>"
            & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>📈 Tendencia mensual de ofertas</div>"
            & "<div style='color:" & _DeltaColor & ";font-size:12px;font-weight:600;'>" & _DeltaIcon & " " & FORMAT ( ABS ( _Delta ), "0.0%" ) & "</div>"
        & "</div>"
        & "<svg viewBox='0 0 " & _Width & " " & _Height & "' width='100%' xmlns='http://www.w3.org/2000/svg'>"
            & "<polyline points='" & _Points & "' stroke='#00D4FF' stroke-width='2' fill='none' stroke-linejoin='round' stroke-linecap='round'/>"
        & "</svg>"
        & "<div style='display:flex;justify-content:space-between;font-size:10px;color:#9090A8;margin-top:4px;'>"
            & "<span>min " & FORMAT ( _Min, "#,##0" ) & "</span>"
            & "<span>max " & FORMAT ( _Max, "#,##0" ) & "</span>"
        & "</div>"
    & "</div>"


// ════════════════════════════════════════════════════════════════════════════
//  P2 · ANÁLISIS DE SKILLS
// ════════════════════════════════════════════════════════════════════════════

HTML P2 · Titulo =
"<div style='font-family:Segoe UI,Arial,sans-serif;padding:8px 0;'>"
& "<div style='color:#00D4FF;font-size:24px;font-weight:300;'>🎯 Analisis de Skills</div>"
& "<div style='color:#9090A8;font-size:13px;margin-top:4px;'>Ranking, categorias y evolucion temporal</div>"
& "</div>"


HTML P2 · KPI Skills Activas =
VAR _Activas = COUNTROWS ( FILTER ( VALUES ( Dim_Skills[skill] ), CALCULATE ( COUNTROWS ( Fact_Skills_Oferta ) ) > 0 ) )
VAR _Total   = COUNTROWS ( ALL ( Dim_Skills[skill] ) )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #00D4FF;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>🎯 Skills Activas</div>"
        & "<div style='color:#00D4FF;font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>" & FORMAT ( _Activas, "#,##0" ) & "<span style='color:#9090A8;font-size:18px;'> / " & FORMAT ( _Total, "#,##0" ) & "</span></div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>del catalogo monitoreado</div>"
    & "</div>"


HTML P2 · KPI Skill Lider =
VAR _Top = TOPN ( 1, SUMMARIZE ( Fact_Skills_Oferta, Dim_Skills[skill], "C", COUNTROWS ( Fact_Skills_Oferta ) ), [C], DESC )
VAR _Nombre = CONCATENATEX ( _Top, Dim_Skills[skill] )
VAR _Count  = SUMX ( _Top, [C] )
VAR _Pct    = DIVIDE ( _Count, [Total Ofertas] )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #FFB020;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>🥇 Skill Lider</div>"
        & "<div style='color:#FFB020;font-size:32px;font-weight:300;line-height:1.1;margin-top:8px;'>" & IF ( ISBLANK ( _Nombre ), "—", _Nombre ) & "</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>Presente en " & FORMAT ( _Pct, "0.0%" ) & " de las ofertas</div>"
    & "</div>"


HTML P2 · Tabla Top 10 Skills =
VAR _Top =
    TOPN (
        10,
        SUMMARIZE ( Fact_Skills_Oferta, Dim_Skills[skill],
            "Cnt", COUNTROWS ( Fact_Skills_Oferta ),
            "Pct", DIVIDE ( COUNTROWS ( Fact_Skills_Oferta ), [Total Ofertas] )
        ),
        [Cnt], DESC
    )
VAR _Rows =
    CONCATENATEX (
        _Top,
        "<tr><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;'>" & Dim_Skills[skill]
            & "</td><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;text-align:right;color:#00D4FF;font-weight:600;'>" & FORMAT ( [Cnt], "#,##0" )
            & "</td><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;text-align:right;color:#9090A8;'>" & FORMAT ( [Pct], "0.0%" )
        & "</td></tr>",
        "",
        [Cnt], DESC
    )
RETURN
    "<div style='background:#1A1A2E;padding:20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;'>"
        & "<div style='color:#00D4FF;font-size:14px;font-weight:600;margin-bottom:12px;'>🏆 Top 10 Skills</div>"
        & "<table style='width:100%;border-collapse:collapse;font-size:13px;'>"
            & "<thead><tr style='color:#9090A8;text-transform:uppercase;font-size:10px;letter-spacing:1px;'>"
                & "<th style='padding:6px 12px;text-align:left;border-bottom:1px solid #7B2FBE;'>Skill</th>"
                & "<th style='padding:6px 12px;text-align:right;border-bottom:1px solid #7B2FBE;'>Ofertas</th>"
                & "<th style='padding:6px 12px;text-align:right;border-bottom:1px solid #7B2FBE;'>%</th>"
            & "</tr></thead><tbody>" & _Rows & "</tbody></table>"
    & "</div>"


HTML P2 · Skill Badge Dinamico =
VAR _S    = SELECTEDVALUE ( Dim_Skills[skill], "—" )
VAR _Cat  = SELECTEDVALUE ( Dim_Skills[categoria], "—" )
VAR _Prem = SELECTEDVALUE ( Dim_Skills[es_premium], FALSE )
VAR _Bg =
    SWITCH (
        _Cat,
        "Lenguajes", "#00D4FF",  "BI", "#7B2FBE",  "Cloud", "#00E396",
        "ML/AI", "#FFB020",      "Bases de Datos", "#FF4D6D",
        "Big Data", "#5B8FF9",   "Orquestacion", "#9C7DFF",
        "DevOps", "#00B4D8",     "Librerias", "#C77DFF",
        "Automatizacion", "#06D6A0",
        "#9090A8"
    )
VAR _Ic = IF ( _Prem, " ⭐", "" )
RETURN
    "<div style='font-family:Segoe UI,Arial,sans-serif;padding:8px 0;'>"
        & "<span style='display:inline-block;background:" & _Bg & "22;border:1px solid " & _Bg & ";color:" & _Bg & ";padding:6px 16px;border-radius:16px;font-size:14px;font-weight:600;'>" & _S & _Ic & "</span>"
        & "<span style='color:#9090A8;font-size:11px;margin-left:8px;'>" & _Cat & "</span>"
    & "</div>"


HTML P2 · Banner Categoria Lider =
VAR _Top = TOPN ( 1, SUMMARIZE ( Fact_Skills_Oferta, Dim_Skills[categoria], "C", COUNTROWS ( Fact_Skills_Oferta ) ), [C], DESC )
VAR _Nombre = CONCATENATEX ( _Top, Dim_Skills[categoria] )
VAR _Count  = SUMX ( _Top, [C] )
RETURN
    "<div style='background:#1A1A2E;padding:16px 20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;font-size:14px;border-left:3px solid #7B2FBE;'>"
        & "<span style='color:#9090A8;'>🎯 Categoria mas demandada:</span> "
        & "<b style='color:#7B2FBE;'>" & IF ( ISBLANK ( _Nombre ), "—", _Nombre ) & "</b> con "
        & "<b style='color:#00D4FF;'>" & FORMAT ( _Count, "#,##0" ) & "</b> menciones acumuladas."
    & "</div>"


// ════════════════════════════════════════════════════════════════════════════
//  P3 · INTELIGENCIA SALARIAL
// ════════════════════════════════════════════════════════════════════════════

HTML P3 · Titulo =
"<div style='font-family:Segoe UI,Arial,sans-serif;padding:8px 0;'>"
& "<div style='color:#00D4FF;font-size:24px;font-weight:300;'>💰 Inteligencia Salarial</div>"
& "<div style='color:#9090A8;font-size:13px;margin-top:4px;'>Distribuciones, brechas y drivers del modelo de regresion (R² = 0.93)</div>"
& "</div>"


HTML P3 · KPI Salario Promedio =
VAR _Avg = [Salario Promedio USD]
VAR _Max = [Salario Maximo USD]
VAR _Min = [Salario Minimo USD]
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #7B2FBE;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>💵 Salario Promedio</div>"
        & "<div style='color:#7B2FBE;font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>$" & FORMAT ( DIVIDE ( _Avg, 1000 ), "0.0" ) & "K</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>Min $" & FORMAT ( DIVIDE ( _Min, 1000 ), "0" ) & "K - Max $" & FORMAT ( DIVIDE ( _Max, 1000 ), "0" ) & "K</div>"
    & "</div>"


HTML P3 · KPI Brecha Senior Junior =
VAR _B = [Brecha Salarial Senior vs Junior]
VAR _Color = IF ( _B >= 1.5, "#FF4D6D", IF ( _B >= 1, "#FFB020", "#00E396" ) )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid " & _Color & ";'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>📊 Brecha Senior vs Junior</div>"
        & "<div style='color:" & _Color & ";font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>+" & FORMAT ( _B, "0.0%" ) & "</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>Un Senior gana esto mas que un Junior</div>"
    & "</div>"


HTML P3 · KPI R2 Modelo =
VAR _R2   = 0.93
VAR _RMSE = 14623
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #00E396;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>📈 Calidad del Modelo</div>"
        & "<div style='color:#00E396;font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>R² = " & FORMAT ( _R2, "0.00" ) & "</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>RMSE ± $" & FORMAT ( DIVIDE ( _RMSE, 1000 ), "0" ) & "K USD</div>"
    & "</div>"


HTML P3 · Banner Top Driver Salario =
VAR _Top =
    TOPN ( 1,
        FILTER (
            SUMMARIZE ( Fact_Coef_Salarios, Fact_Coef_Salarios[feature_legible], Fact_Coef_Salarios[categoria_feature] ),
            [Impacto Feature Pct] > 0 && Fact_Coef_Salarios[categoria_feature] = "Skill"
        ),
        [Impacto Feature Pct], DESC
    )
VAR _N = CONCATENATEX ( _Top, Fact_Coef_Salarios[feature_legible] )
VAR _I = SUMX ( _Top, [Impacto Feature Pct] )
RETURN
    "<div style='background:#1A1A2E;padding:16px 20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;font-size:14px;border-left:3px solid #FFB020;'>"
        & "<span style='color:#9090A8;'>💡 Insight del modelo:</span> "
        & "Dominar <b style='color:#FFB020;'>" & IF ( ISBLANK ( _N ), "—", _N ) & "</b> "
        & "aumenta el salario esperado en <b style='color:#00E396;'>+" & FORMAT ( _I, "0.0" ) & "%</b> ceteris paribus."
    & "</div>"


HTML P3 · Salary Calculator =
VAR _Pred = [Salario Predicho USD]
VAR _Real = [Salario Mediano USD]
RETURN
    "<div style='background:#1A1A2E;padding:24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;margin-bottom:12px;'>🧠 Salary Calculator</div>"
        & "<div style='color:#00D4FF;font-size:32px;font-weight:300;'>Estimado: $" & FORMAT ( DIVIDE ( _Pred, 1000 ), "0.0" ) & "K USD/ano</div>"
        & "<div style='color:#9090A8;font-size:13px;margin-top:8px;'>Salario observado mediano para el perfil: <b style='color:#7B2FBE;'>$" & FORMAT ( DIVIDE ( _Real, 1000 ), "0.0" ) & "K</b></div>"
        & "<div style='color:#9090A8;font-size:11px;margin-top:12px;font-style:italic;'>Ajusta los slicers (rol, nivel, pais, skills) para recalcular.</div>"
    & "</div>"


HTML P3 · Tabla Top 5 Drivers =
VAR _Top =
    TOPN ( 5,
        FILTER (
            SUMMARIZE ( Fact_Coef_Salarios, Fact_Coef_Salarios[feature_legible], Fact_Coef_Salarios[categoria_feature] ),
            [Impacto Feature Pct] > 0
        ),
        [Impacto Feature Pct], DESC
    )
VAR _Rows =
    CONCATENATEX (
        _Top,
        "<tr><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;color:#E8E8F0;'>" & Fact_Coef_Salarios[feature_legible]
            & "</td><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;color:#9090A8;font-size:11px;'>" & Fact_Coef_Salarios[categoria_feature]
            & "</td><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;text-align:right;color:#00E396;font-weight:600;'>+" & FORMAT ( [Impacto Feature Pct], "0.0" ) & "%</td></tr>",
        "",
        [Impacto Feature Pct], DESC
    )
RETURN
    "<div style='background:#1A1A2E;padding:20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;'>"
        & "<div style='color:#00D4FF;font-size:14px;font-weight:600;margin-bottom:12px;'>✨ Top 5 Drivers Positivos</div>"
        & "<table style='width:100%;border-collapse:collapse;font-size:13px;'>"
            & "<thead><tr style='color:#9090A8;text-transform:uppercase;font-size:10px;letter-spacing:1px;'>"
                & "<th style='padding:6px 12px;text-align:left;border-bottom:1px solid #7B2FBE;'>Feature</th>"
                & "<th style='padding:6px 12px;text-align:left;border-bottom:1px solid #7B2FBE;'>Categoria</th>"
                & "<th style='padding:6px 12px;text-align:right;border-bottom:1px solid #7B2FBE;'>Impacto</th>"
            & "</tr></thead><tbody>" & _Rows & "</tbody></table>"
    & "</div>"


HTML P3 · Boxplot Salario por Nivel =
// SVG boxplot horizontal con la distribución de salarios (min, Q1, mediana, Q3, max)
// por nivel de experiencia. Ordenado Junior → Lead de arriba a abajo.
VAR _W = 360
VAR _H = 220
VAR _LP = 70
VAR _RP = 20
VAR _PW = _W - _LP - _RP
VAR _MinAll = CALCULATE ( MIN ( Fact_Ofertas[salario_anual_usd] ), ALL ( Fact_Ofertas[nivel_experiencia] ) )
VAR _MaxAll = CALCULATE ( MAX ( Fact_Ofertas[salario_anual_usd] ), ALL ( Fact_Ofertas[nivel_experiencia] ) )
VAR _Range  = _MaxAll - _MinAll + 0.0001
VAR _Niveles =
    ADDCOLUMNS (
        SUMMARIZE ( Fact_Ofertas, Fact_Ofertas[nivel_experiencia] ),
        "Ord", SWITCH ( Fact_Ofertas[nivel_experiencia], "Junior", 1, "Mid", 2, "Senior", 3, "Lead", 4, 99 )
    )
VAR _Stats =
    ADDCOLUMNS (
        _Niveles,
        "Q1",  CALCULATE ( PERCENTILEX.INC ( Fact_Ofertas, Fact_Ofertas[salario_anual_usd], 0.25 ) ),
        "Med", CALCULATE ( PERCENTILEX.INC ( Fact_Ofertas, Fact_Ofertas[salario_anual_usd], 0.50 ) ),
        "Q3",  CALCULATE ( PERCENTILEX.INC ( Fact_Ofertas, Fact_Ofertas[salario_anual_usd], 0.75 ) ),
        "Mn",  CALCULATE ( MIN ( Fact_Ofertas[salario_anual_usd] ) ),
        "Mx",  CALCULATE ( MAX ( Fact_Ofertas[salario_anual_usd] ) )
    )
VAR _Boxes =
    CONCATENATEX (
        _Stats,
        VAR _Y    = 30 + ( [Ord] - 1 ) * 42
        VAR _XMin = _LP + DIVIDE ( [Mn]  - _MinAll, _Range ) * _PW
        VAR _XQ1  = _LP + DIVIDE ( [Q1]  - _MinAll, _Range ) * _PW
        VAR _XMed = _LP + DIVIDE ( [Med] - _MinAll, _Range ) * _PW
        VAR _XQ3  = _LP + DIVIDE ( [Q3]  - _MinAll, _Range ) * _PW
        VAR _XMax = _LP + DIVIDE ( [Mx]  - _MinAll, _Range ) * _PW
        RETURN
            "<text x='" & _LP - 8 & "' y='" & _Y + 4 & "' fill='#E8E8F0' font-size='11' font-family='Segoe UI' text-anchor='end'>" & Fact_Ofertas[nivel_experiencia] & "</text>"
            & "<line x1='" & FORMAT ( _XMin, "0" ) & "' y1='" & _Y & "' x2='" & FORMAT ( _XMax, "0" ) & "' y2='" & _Y & "' stroke='#7B2FBE' stroke-width='1' stroke-opacity='0.5'/>"
            & "<line x1='" & FORMAT ( _XMin, "0" ) & "' y1='" & _Y - 6 & "' x2='" & FORMAT ( _XMin, "0" ) & "' y2='" & _Y + 6 & "' stroke='#7B2FBE' stroke-width='1'/>"
            & "<line x1='" & FORMAT ( _XMax, "0" ) & "' y1='" & _Y - 6 & "' x2='" & FORMAT ( _XMax, "0" ) & "' y2='" & _Y + 6 & "' stroke='#7B2FBE' stroke-width='1'/>"
            & "<rect x='" & FORMAT ( _XQ1, "0" ) & "' y='" & _Y - 12 & "' width='" & FORMAT ( _XQ3 - _XQ1, "0" ) & "' height='24' fill='#7B2FBE' fill-opacity='0.35' stroke='#7B2FBE' stroke-width='1'/>"
            & "<line x1='" & FORMAT ( _XMed, "0" ) & "' y1='" & _Y - 12 & "' x2='" & FORMAT ( _XMed, "0" ) & "' y2='" & _Y + 12 & "' stroke='#00D4FF' stroke-width='2'/>",
        "",
        [Ord], ASC
    )
RETURN
    "<div style='background:#1A1A2E;padding:16px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;margin-bottom:12px;'>💰 Distribución salarial por nivel</div>"
        & "<svg viewBox='0 0 " & _W & " " & _H & "' width='100%' xmlns='http://www.w3.org/2000/svg'>"
            & _Boxes
            & "<line x1='" & _LP & "' y1='195' x2='" & _W - _RP & "' y2='195' stroke='#9090A8' stroke-width='0.5'/>"
            & "<text x='" & _LP & "' y='210' fill='#9090A8' font-size='10' font-family='Segoe UI'>$" & FORMAT ( DIVIDE ( _MinAll, 1000 ), "0" ) & "K</text>"
            & "<text x='" & _W - _RP & "' y='210' fill='#9090A8' font-size='10' font-family='Segoe UI' text-anchor='end'>$" & FORMAT ( DIVIDE ( _MaxAll, 1000 ), "0" ) & "K</text>"
        & "</svg>"
        & "<div style='display:flex;gap:14px;font-size:10px;color:#9090A8;margin-top:8px;'>"
            & "<span><span style='display:inline-block;width:10px;height:10px;background:#7B2FBE;opacity:0.35;'></span> Q1–Q3</span>"
            & "<span><span style='color:#00D4FF;font-weight:600;'>│</span> Mediana</span>"
            & "<span><span style='color:#7B2FBE;'>──</span> Rango min–max</span>"
        & "</div>"
    & "</div>"


HTML P3 · Boxplot Salario por Rol =
// SVG boxplot horizontal por rol_normalizado, ordenado por mediana ascendente
// (de menor a mayor salario mediano).
VAR _W = 360
VAR _H = 380
VAR _LP = 100
VAR _RP = 20
VAR _PW = _W - _LP - _RP
VAR _MinAll = CALCULATE ( MIN ( Fact_Ofertas[salario_anual_usd] ), ALL ( Fact_Ofertas[rol_normalizado] ) )
VAR _MaxAll = CALCULATE ( MAX ( Fact_Ofertas[salario_anual_usd] ), ALL ( Fact_Ofertas[rol_normalizado] ) )
VAR _Range  = _MaxAll - _MinAll + 0.0001
VAR _Roles =
    ADDCOLUMNS (
        SUMMARIZE ( Fact_Ofertas, Fact_Ofertas[rol_normalizado] ),
        "Med", CALCULATE ( PERCENTILEX.INC ( Fact_Ofertas, Fact_Ofertas[salario_anual_usd], 0.50 ) )
    )
VAR _RolesOrd = ADDCOLUMNS ( _Roles, "Ord", RANKX ( _Roles, [Med], , ASC, DENSE ) )
VAR _Stats =
    ADDCOLUMNS (
        _RolesOrd,
        "Q1", CALCULATE ( PERCENTILEX.INC ( Fact_Ofertas, Fact_Ofertas[salario_anual_usd], 0.25 ) ),
        "Q3", CALCULATE ( PERCENTILEX.INC ( Fact_Ofertas, Fact_Ofertas[salario_anual_usd], 0.75 ) ),
        "Mn", CALCULATE ( MIN ( Fact_Ofertas[salario_anual_usd] ) ),
        "Mx", CALCULATE ( MAX ( Fact_Ofertas[salario_anual_usd] ) )
    )
VAR _Boxes =
    CONCATENATEX (
        _Stats,
        VAR _Y    = 30 + ( [Ord] - 1 ) * 38
        VAR _XMin = _LP + DIVIDE ( [Mn]  - _MinAll, _Range ) * _PW
        VAR _XQ1  = _LP + DIVIDE ( [Q1]  - _MinAll, _Range ) * _PW
        VAR _XMed = _LP + DIVIDE ( [Med] - _MinAll, _Range ) * _PW
        VAR _XQ3  = _LP + DIVIDE ( [Q3]  - _MinAll, _Range ) * _PW
        VAR _XMax = _LP + DIVIDE ( [Mx]  - _MinAll, _Range ) * _PW
        RETURN
            "<text x='" & _LP - 8 & "' y='" & _Y + 4 & "' fill='#E8E8F0' font-size='10' font-family='Segoe UI' text-anchor='end'>" & Fact_Ofertas[rol_normalizado] & "</text>"
            & "<line x1='" & FORMAT ( _XMin, "0" ) & "' y1='" & _Y & "' x2='" & FORMAT ( _XMax, "0" ) & "' y2='" & _Y & "' stroke='#7B2FBE' stroke-width='1' stroke-opacity='0.5'/>"
            & "<rect x='" & FORMAT ( _XQ1, "0" ) & "' y='" & _Y - 10 & "' width='" & FORMAT ( _XQ3 - _XQ1, "0" ) & "' height='20' fill='#7B2FBE' fill-opacity='0.35' stroke='#7B2FBE' stroke-width='1'/>"
            & "<line x1='" & FORMAT ( _XMed, "0" ) & "' y1='" & _Y - 10 & "' x2='" & FORMAT ( _XMed, "0" ) & "' y2='" & _Y + 10 & "' stroke='#00D4FF' stroke-width='2'/>",
        "",
        [Ord], ASC
    )
RETURN
    "<div style='background:#1A1A2E;padding:16px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;margin-bottom:12px;'>🎯 Distribución salarial por rol (ordenado por mediana)</div>"
        & "<svg viewBox='0 0 " & _W & " " & _H & "' width='100%' xmlns='http://www.w3.org/2000/svg'>"
            & _Boxes
            & "<line x1='" & _LP & "' y1='350' x2='" & _W - _RP & "' y2='350' stroke='#9090A8' stroke-width='0.5'/>"
            & "<text x='" & _LP & "' y='365' fill='#9090A8' font-size='10' font-family='Segoe UI'>$" & FORMAT ( DIVIDE ( _MinAll, 1000 ), "0" ) & "K</text>"
            & "<text x='" & _W - _RP & "' y='365' fill='#9090A8' font-size='10' font-family='Segoe UI' text-anchor='end'>$" & FORMAT ( DIVIDE ( _MaxAll, 1000 ), "0" ) & "K</text>"
        & "</svg>"
    & "</div>"


// ════════════════════════════════════════════════════════════════════════════
//  P4 · MAPA GEOGRÁFICO
// ════════════════════════════════════════════════════════════════════════════

HTML P4 · Titulo =
"<div style='font-family:Segoe UI,Arial,sans-serif;padding:8px 0;'>"
& "<div style='color:#00D4FF;font-size:24px;font-weight:300;'>🌎 Mapa Geografico</div>"
& "<div style='color:#9090A8;font-size:13px;margin-top:4px;'>Distribucion de ofertas por ciudad y pais</div>"
& "</div>"


HTML P4 · KPI Total Paises =
VAR _Paises   = DISTINCTCOUNT ( Fact_Ofertas[pais] )
VAR _Ciudades = DISTINCTCOUNT ( Fact_Ofertas[ciudad] )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #00D4FF;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>🌎 Cobertura Geografica</div>"
        & "<div style='color:#00D4FF;font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>" & FORMAT ( _Paises, "#,##0" ) & "<span style='color:#9090A8;font-size:18px;'> paises</span></div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>" & FORMAT ( _Ciudades, "#,##0" ) & " ciudades distintas</div>"
    & "</div>"


HTML P4 · KPI Ciudad Lider =
VAR _Top = TOPN ( 1, VALUES ( Fact_Ofertas[ciudad] ), CALCULATE ( COUNTROWS ( Fact_Ofertas ) ), DESC )
VAR _Nombre = CONCATENATEX ( _Top, Fact_Ofertas[ciudad] )
VAR _N = CALCULATE ( COUNTROWS ( Fact_Ofertas ), TREATAS ( _Top, Fact_Ofertas[ciudad] ) )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #7B2FBE;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>📍 Ciudad Lider</div>"
        & "<div style='color:#7B2FBE;font-size:32px;font-weight:300;line-height:1.1;margin-top:8px;'>" & IF ( ISBLANK ( _Nombre ), "—", _Nombre ) & "</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>" & FORMAT ( _N, "#,##0" ) & " ofertas en el periodo</div>"
    & "</div>"


HTML P4 · KPI Mejor Mercado Salarial =
VAR _Top = TOPN ( 1, FILTER ( VALUES ( Fact_Ofertas[pais] ), CALCULATE ( COUNTROWS ( Fact_Ofertas ) ) >= 50 ), CALCULATE ( [Salario Mediano USD] ), DESC )
VAR _Nombre = CONCATENATEX ( _Top, Fact_Ofertas[pais] )
VAR _Sal = CALCULATE ( [Salario Mediano USD], TREATAS ( _Top, Fact_Ofertas[pais] ) )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #00E396;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>💵 Mejor Mercado Salarial</div>"
        & "<div style='color:#00E396;font-size:28px;font-weight:300;line-height:1.1;margin-top:8px;'>" & IF ( ISBLANK ( _Nombre ), "—", _Nombre ) & "</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>Mediana: $" & FORMAT ( DIVIDE ( _Sal, 1000 ), "0.0" ) & "K USD/ano (min 50 ofertas)</div>"
    & "</div>"


HTML P4 · Tabla Top 8 Ciudades =
VAR _Top =
    TOPN ( 8,
        SUMMARIZE ( Fact_Ofertas, Fact_Ofertas[ciudad], Fact_Ofertas[pais],
            "N", COUNTROWS ( Fact_Ofertas ),
            "Sal", [Salario Mediano USD]
        ),
        [N], DESC
    )
VAR _Rows =
    CONCATENATEX (
        _Top,
        "<tr><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;color:#E8E8F0;'>" & Fact_Ofertas[ciudad]
            & "</td><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;color:#9090A8;font-size:11px;'>" & Fact_Ofertas[pais]
            & "</td><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;text-align:right;color:#00D4FF;font-weight:600;'>" & FORMAT ( [N], "#,##0" )
            & "</td><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;text-align:right;color:#00E396;'>$" & FORMAT ( DIVIDE ( [Sal], 1000 ), "0" ) & "K</td></tr>",
        "",
        [N], DESC
    )
RETURN
    "<div style='background:#1A1A2E;padding:20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;'>"
        & "<div style='color:#00D4FF;font-size:14px;font-weight:600;margin-bottom:12px;'>🏙️ Top 8 Ciudades</div>"
        & "<table style='width:100%;border-collapse:collapse;font-size:13px;'>"
            & "<thead><tr style='color:#9090A8;text-transform:uppercase;font-size:10px;letter-spacing:1px;'>"
                & "<th style='padding:6px 12px;text-align:left;border-bottom:1px solid #7B2FBE;'>Ciudad</th>"
                & "<th style='padding:6px 12px;text-align:left;border-bottom:1px solid #7B2FBE;'>Pais</th>"
                & "<th style='padding:6px 12px;text-align:right;border-bottom:1px solid #7B2FBE;'>Ofertas</th>"
                & "<th style='padding:6px 12px;text-align:right;border-bottom:1px solid #7B2FBE;'>Mediana</th>"
            & "</tr></thead><tbody>" & _Rows & "</tbody></table>"
    & "</div>"


// ════════════════════════════════════════════════════════════════════════════
//  P5 · PREDICCIONES PROPHET
// ════════════════════════════════════════════════════════════════════════════

HTML P5 · Titulo =
"<div style='font-family:Segoe UI,Arial,sans-serif;padding:8px 0;'>"
& "<div style='color:#00D4FF;font-size:24px;font-weight:300;'>🔮 Predicciones Prophet</div>"
& "<div style='color:#9090A8;font-size:13px;margin-top:4px;'>Forecast 12 meses con intervalos de confianza al 80%</div>"
& "</div>"


HTML P5 · KPI Skill Seleccionada =
VAR _S      = SELECTEDVALUE ( Fact_Predicciones[skill], "(Selecciona una skill)" )
VAR _Future = CALCULATE ( AVERAGE ( Fact_Predicciones[prediccion] ),     Fact_Predicciones[historico] = FALSE )
VAR _Low    = CALCULATE ( AVERAGE ( Fact_Predicciones[banda_inferior] ), Fact_Predicciones[historico] = FALSE )
VAR _High   = CALCULATE ( AVERAGE ( Fact_Predicciones[banda_superior] ), Fact_Predicciones[historico] = FALSE )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #00D4FF;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>🔮 Forecast Promedio 12m</div>"
        & "<div style='color:#00D4FF;font-size:28px;font-weight:300;line-height:1.1;margin-top:8px;'>" & _S & "</div>"
        & "<div style='color:#FFB020;font-size:18px;margin-top:8px;'>" & FORMAT ( _Future, "#,##0.0" ) & " menciones/mes</div>"
        & "<div style='color:#9090A8;font-size:11px;margin-top:6px;'>IC 80%: " & FORMAT ( _Low, "#,##0" ) & " - " & FORMAT ( _High, "#,##0" ) & "</div>"
    & "</div>"


HTML P5 · KPI Crecimiento Esperado =
VAR _Crec  = [Crecimiento Esperado Skill]
VAR _Color = IF ( NOT ISBLANK ( _Crec ) && _Crec > 0, "#00E396", "#FF4D6D" )
VAR _Icono = IF ( NOT ISBLANK ( _Crec ) && _Crec > 0, "📈", "📉" )
VAR _Texto = IF ( ISBLANK ( _Crec ), "Sin datos", FORMAT ( ABS ( _Crec ), "0.0%" ) & IF ( _Crec > 0, " al alza", " a la baja" ) )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid " & _Color & ";'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>" & _Icono & " Crecimiento Esperado 12m</div>"
        & "<div style='color:" & _Color & ";font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>" & _Texto & "</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>Forecast vs ultimo historico observado</div>"
    & "</div>"


HTML P5 · Banner Forecast Info =
VAR _Skills = DISTINCTCOUNT ( Fact_Predicciones[skill] )
VAR _Meses  = CALCULATE ( DISTINCTCOUNT ( Fact_Predicciones[fecha] ), Fact_Predicciones[historico] = FALSE )
RETURN
    "<div style='background:#1A1A2E;padding:14px 20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;font-size:13px;border-left:3px solid #7B2FBE;'>"
        & "<span style='color:#9090A8;'>📊 Modelo:</span> <b>Prophet</b> (Meta) con estacionalidad anual y intervalos de confianza al 80%. "
        & "Forecast generado para <b style='color:#00D4FF;'>" & _Skills & " skills</b> a <b style='color:#FFB020;'>" & _Meses & " meses vista</b>."
    & "</div>"


HTML P5 · Tabla Top 5 Emergentes =
VAR _SkillsConCresc =
    ADDCOLUMNS (
        VALUES ( Fact_Predicciones[skill] ),
        "Cresc",
            VAR _UH = CALCULATE ( AVERAGE ( Fact_Predicciones[prediccion] ), Fact_Predicciones[historico] = TRUE )
            VAR _UF = CALCULATE ( AVERAGE ( Fact_Predicciones[prediccion] ), Fact_Predicciones[historico] = FALSE )
            RETURN DIVIDE ( _UF - _UH, _UH )
    )
VAR _Top = TOPN ( 5, FILTER ( _SkillsConCresc, [Cresc] > 0 ), [Cresc], DESC )
VAR _Rows =
    CONCATENATEX (
        _Top,
        "<tr><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;color:#E8E8F0;'>" & Fact_Predicciones[skill]
            & "</td><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;text-align:right;color:#00E396;font-weight:600;'>+" & FORMAT ( [Cresc], "0.0%" ) & "</td></tr>",
        "",
        [Cresc], DESC
    )
RETURN
    "<div style='background:#1A1A2E;padding:20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;'>"
        & "<div style='color:#00E396;font-size:14px;font-weight:600;margin-bottom:12px;'>🚀 Top 5 Skills Emergentes</div>"
        & "<table style='width:100%;border-collapse:collapse;font-size:13px;'>"
            & "<thead><tr style='color:#9090A8;text-transform:uppercase;font-size:10px;letter-spacing:1px;'>"
                & "<th style='padding:6px 12px;text-align:left;border-bottom:1px solid #00E396;'>Skill</th>"
                & "<th style='padding:6px 12px;text-align:right;border-bottom:1px solid #00E396;'>Crecimiento 12m</th>"
            & "</tr></thead><tbody>" & _Rows & "</tbody></table>"
    & "</div>"


HTML P5 · Tabla Top 5 Declinando =
VAR _SkillsConCresc =
    ADDCOLUMNS (
        VALUES ( Fact_Predicciones[skill] ),
        "Cresc",
            VAR _UH = CALCULATE ( AVERAGE ( Fact_Predicciones[prediccion] ), Fact_Predicciones[historico] = TRUE )
            VAR _UF = CALCULATE ( AVERAGE ( Fact_Predicciones[prediccion] ), Fact_Predicciones[historico] = FALSE )
            RETURN DIVIDE ( _UF - _UH, _UH )
    )
VAR _Bot = TOPN ( 5, FILTER ( _SkillsConCresc, [Cresc] < 0 ), [Cresc], ASC )
VAR _Rows =
    CONCATENATEX (
        _Bot,
        "<tr><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;color:#E8E8F0;'>" & Fact_Predicciones[skill]
            & "</td><td style='padding:6px 12px;border-bottom:1px solid #2A2A45;text-align:right;color:#FF4D6D;font-weight:600;'>" & FORMAT ( [Cresc], "0.0%" ) & "</td></tr>",
        "",
        [Cresc], ASC
    )
RETURN
    "<div style='background:#1A1A2E;padding:20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;'>"
        & "<div style='color:#FF4D6D;font-size:14px;font-weight:600;margin-bottom:12px;'>📉 Top 5 Skills en Declive</div>"
        & "<table style='width:100%;border-collapse:collapse;font-size:13px;'>"
            & "<thead><tr style='color:#9090A8;text-transform:uppercase;font-size:10px;letter-spacing:1px;'>"
                & "<th style='padding:6px 12px;text-align:left;border-bottom:1px solid #FF4D6D;'>Skill</th>"
                & "<th style='padding:6px 12px;text-align:right;border-bottom:1px solid #FF4D6D;'>Caida 12m</th>"
            & "</tr></thead><tbody>" & _Rows & "</tbody></table>"
    & "</div>"


HTML P5 · Linea Forecast con Banda =
// SVG con: línea histórica (azul continua), línea forecast (violeta punteada),
// banda de confianza 80% (polígono violeta semi-transparente). Filtrar por
// skill en slicer; sin filtro muestra el promedio sobre todas las skills.
VAR _W   = 360
VAR _H   = 180
VAR _Pad = 15
VAR _Data =
    ADDCOLUMNS (
        SUMMARIZE ( Fact_Predicciones, Fact_Predicciones[fecha], Fact_Predicciones[historico] ),
        "Y",  CALCULATE ( AVERAGE ( Fact_Predicciones[prediccion] ) ),
        "Lo", CALCULATE ( AVERAGE ( Fact_Predicciones[banda_inferior] ) ),
        "Hi", CALCULATE ( AVERAGE ( Fact_Predicciones[banda_superior] ) )
    )
VAR _Ranked = ADDCOLUMNS ( _Data, "Idx", RANKX ( _Data, Fact_Predicciones[fecha], , ASC, DENSE ) )
VAR _MaxY  = MAXX ( _Ranked, [Hi] ) + 0.0001
VAR _MinY  = MINX ( _Ranked, [Lo] )
VAR _RY    = _MaxY - _MinY + 0.0001
VAR _N     = COUNTROWS ( _Ranked ) + 0
VAR _StepX = DIVIDE ( _W - 2 * _Pad, _N - 1 )
VAR _Hist  = FILTER ( _Ranked, Fact_Predicciones[historico] = TRUE )
VAR _Fcst  = FILTER ( _Ranked, Fact_Predicciones[historico] = FALSE )
VAR _HistPts =
    CONCATENATEX ( _Hist,
        FORMAT ( _Pad + ( [Idx] - 1 ) * _StepX, "0" ) & "," &
        FORMAT ( _H - _Pad - DIVIDE ( [Y] - _MinY, _RY ) * ( _H - 2 * _Pad ), "0" ),
        " ", [Idx], ASC
    )
VAR _FcstPts =
    CONCATENATEX ( _Fcst,
        FORMAT ( _Pad + ( [Idx] - 1 ) * _StepX, "0" ) & "," &
        FORMAT ( _H - _Pad - DIVIDE ( [Y] - _MinY, _RY ) * ( _H - 2 * _Pad ), "0" ),
        " ", [Idx], ASC
    )
VAR _UpperPts =
    CONCATENATEX ( _Fcst,
        FORMAT ( _Pad + ( [Idx] - 1 ) * _StepX, "0" ) & "," &
        FORMAT ( _H - _Pad - DIVIDE ( [Hi] - _MinY, _RY ) * ( _H - 2 * _Pad ), "0" ),
        " ", [Idx], ASC
    )
VAR _LowerPts =
    CONCATENATEX ( _Fcst,
        FORMAT ( _Pad + ( [Idx] - 1 ) * _StepX, "0" ) & "," &
        FORMAT ( _H - _Pad - DIVIDE ( [Lo] - _MinY, _RY ) * ( _H - 2 * _Pad ), "0" ),
        " ", [Idx], DESC
    )
VAR _Band = _UpperPts & " " & _LowerPts
VAR _Skill = SELECTEDVALUE ( Fact_Predicciones[skill], "(selecciona una skill)" )
RETURN
    "<div style='background:#1A1A2E;padding:16px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;margin-bottom:4px;'>🔮 Forecast Prophet</div>"
        & "<div style='color:#00D4FF;font-size:14px;font-weight:600;margin-bottom:8px;'>" & _Skill & "</div>"
        & "<svg viewBox='0 0 " & _W & " " & _H & "' width='100%' xmlns='http://www.w3.org/2000/svg'>"
            & "<polygon points='" & _Band & "' fill='#7B2FBE' fill-opacity='0.2'/>"
            & "<polyline points='" & _HistPts & "' stroke='#00D4FF' stroke-width='2' fill='none' stroke-linejoin='round'/>"
            & "<polyline points='" & _FcstPts & "' stroke='#7B2FBE' stroke-width='2' fill='none' stroke-linejoin='round' stroke-dasharray='4,2'/>"
        & "</svg>"
        & "<div style='display:flex;gap:16px;font-size:10px;color:#9090A8;margin-top:8px;'>"
            & "<span><span style='color:#00D4FF;font-weight:600;'>──</span> Histórico</span>"
            & "<span><span style='color:#7B2FBE;font-weight:600;'>─ ─</span> Forecast</span>"
            & "<span><span style='background:#7B2FBE;opacity:0.3;display:inline-block;width:10px;height:10px;'></span> IC 80%</span>"
        & "</div>"
    & "</div>"


// ════════════════════════════════════════════════════════════════════════════
//  P6 · PERFILES / CLUSTERS
// ════════════════════════════════════════════════════════════════════════════

HTML P6 · Titulo =
"<div style='font-family:Segoe UI,Arial,sans-serif;padding:8px 0;'>"
& "<div style='color:#00D4FF;font-size:24px;font-weight:300;'>👥 Perfiles Profesionales</div>"
& "<div style='color:#9090A8;font-size:13px;margin-top:4px;'>Arquetipos identificados via K-means clustering + PCA</div>"
& "</div>"


HTML P6 · KPI Total Arquetipos =
VAR _N   = COUNTROWS ( Dim_Clusters )
VAR _Tot = SUM ( Dim_Clusters[n_ofertas] )
RETURN
    "<div style='background:#1A1A2E;padding:20px 24px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;border-left:3px solid #00D4FF;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;'>👥 Arquetipos Identificados</div>"
        & "<div style='color:#00D4FF;font-size:38px;font-weight:300;line-height:1.1;margin-top:8px;'>" & FORMAT ( _N, "0" ) & "</div>"
        & "<div style='color:#9090A8;font-size:12px;margin-top:8px;'>K-means sobre matriz de skills · " & FORMAT ( _Tot, "#,##0" ) & " ofertas clasificadas</div>"
    & "</div>"


HTML P6 · Cluster Card =
// IMPORTANTE: usar 4 visuales HTML Content, cada uno filtrado a un cluster_id distinto
VAR _Nombre = SELECTEDVALUE ( Dim_Clusters[cluster_nombre], "—" )
VAR _N      = SELECTEDVALUE ( Dim_Clusters[n_ofertas], 0 )
VAR _Pct    = SELECTEDVALUE ( Dim_Clusters[pct_total], 0 )
VAR _Rol    = SELECTEDVALUE ( Dim_Clusters[rol_dominante], "—" )
VAR _Sal    = SELECTEDVALUE ( Dim_Clusters[salario_mediano_usd], 0 )
VAR _Exp    = SELECTEDVALUE ( Dim_Clusters[anios_exp_promedio], 0 )
VAR _Skills = SELECTEDVALUE ( Dim_Clusters[top_skills], "—" )
VAR _Color =
    SWITCH (
        _Rol,
        "Data Analyst",       "#FFB020",
        "Data Scientist",     "#00E396",
        "Data Engineer",      "#00D4FF",
        "Analytics Engineer", "#7B2FBE",
        "ML Engineer",        "#FF4D6D",
        "#9090A8"
    )
RETURN
    "<div style='background:#1A1A2E;padding:20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;border-left:4px solid " & _Color & ";height:100%;'>"
        & "<div style='color:" & _Color & ";font-size:16px;font-weight:600;margin-bottom:4px;'>" & _Nombre & "</div>"
        & "<div style='color:#9090A8;font-size:11px;margin-bottom:12px;'>" & FORMAT ( _N, "#,##0" ) & " ofertas · " & FORMAT ( _Pct, "0.0" ) & "% del total</div>"
        & "<div style='border-top:1px solid #2A2A45;padding-top:10px;margin-top:8px;'>"
            & "<div style='color:#9090A8;font-size:10px;text-transform:uppercase;margin-bottom:4px;'>Salario mediano</div>"
            & "<div style='color:#00E396;font-size:22px;font-weight:300;'>$" & FORMAT ( DIVIDE ( _Sal, 1000 ), "0.0" ) & "K</div>"
            & "<div style='color:#9090A8;font-size:11px;margin-top:8px;'>Experiencia: " & FORMAT ( _Exp, "0.0" ) & " anios</div>"
            & "<div style='color:#9090A8;font-size:11px;margin-top:8px;'>Top skills:</div>"
            & "<div style='color:#E8E8F0;font-size:12px;margin-top:2px;'>" & _Skills & "</div>"
        & "</div>"
    & "</div>"


HTML P6 · Tabla Resumen Clusters =
VAR _Rows =
    CONCATENATEX (
        SUMMARIZE (
            Dim_Clusters,
            Dim_Clusters[cluster_id], Dim_Clusters[cluster_nombre],
            Dim_Clusters[n_ofertas], Dim_Clusters[salario_mediano_usd],
            Dim_Clusters[top_skills]
        ),
        "<tr><td style='padding:8px 12px;border-bottom:1px solid #2A2A45;color:#7B2FBE;font-weight:600;'>" & Dim_Clusters[cluster_nombre]
            & "</td><td style='padding:8px 12px;border-bottom:1px solid #2A2A45;text-align:right;color:#00D4FF;'>" & FORMAT ( Dim_Clusters[n_ofertas], "#,##0" )
            & "</td><td style='padding:8px 12px;border-bottom:1px solid #2A2A45;text-align:right;color:#00E396;'>$" & FORMAT ( DIVIDE ( Dim_Clusters[salario_mediano_usd], 1000 ), "0" ) & "K"
            & "</td><td style='padding:8px 12px;border-bottom:1px solid #2A2A45;color:#9090A8;font-size:11px;'>" & Dim_Clusters[top_skills] & "</td></tr>",
        "",
        Dim_Clusters[n_ofertas], DESC
    )
RETURN
    "<div style='background:#1A1A2E;padding:20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;'>"
        & "<div style='color:#00D4FF;font-size:14px;font-weight:600;margin-bottom:12px;'>👥 Tabla Resumen de Arquetipos</div>"
        & "<table style='width:100%;border-collapse:collapse;font-size:12px;'>"
            & "<thead><tr style='color:#9090A8;text-transform:uppercase;font-size:10px;letter-spacing:1px;'>"
                & "<th style='padding:8px 12px;text-align:left;border-bottom:1px solid #7B2FBE;'>Arquetipo</th>"
                & "<th style='padding:8px 12px;text-align:right;border-bottom:1px solid #7B2FBE;'>Ofertas</th>"
                & "<th style='padding:8px 12px;text-align:right;border-bottom:1px solid #7B2FBE;'>Mediana</th>"
                & "<th style='padding:8px 12px;text-align:left;border-bottom:1px solid #7B2FBE;'>Top Skills</th>"
            & "</tr></thead><tbody>" & _Rows & "</tbody></table>"
    & "</div>"


HTML P6 · Banner Insight Cluster =
VAR _Mayor = TOPN ( 1, VALUES ( Dim_Clusters[cluster_nombre] ), CALCULATE ( SUM ( Dim_Clusters[n_ofertas] ) ), DESC )
VAR _Rico  = TOPN ( 1, VALUES ( Dim_Clusters[cluster_nombre] ), CALCULATE ( MAX ( Dim_Clusters[salario_mediano_usd] ) ), DESC )
VAR _NombreM = CONCATENATEX ( _Mayor, Dim_Clusters[cluster_nombre] )
VAR _NombreR = CONCATENATEX ( _Rico,  Dim_Clusters[cluster_nombre] )
VAR _SalR = CALCULATE ( MAX ( Dim_Clusters[salario_mediano_usd] ), TREATAS ( _Rico, Dim_Clusters[cluster_nombre] ) )
RETURN
    "<div style='background:#1A1A2E;padding:16px 20px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;color:#E8E8F0;font-size:14px;border-left:3px solid #00D4FF;line-height:1.6;'>"
        & "<span style='color:#9090A8;'>💡 Insight de clustering:</span> "
        & "El arquetipo mas numeroso es <b style='color:#00D4FF;'>" & _NombreM & "</b>, "
        & "mientras que el mejor remunerado es <b style='color:#00E396;'>" & _NombreR & "</b> "
        & "con una mediana de <b>$" & FORMAT ( DIVIDE ( _SalR, 1000 ), "0.0" ) & "K USD</b>."
    & "</div>"


HTML P6 · Bars Comparativo Clusters =
// Bars comparativas (CSS, no SVG) con 2 métricas por cluster: # ofertas y
// salario mediano. Color del nombre = color asociado al rol dominante.
VAR _Data =
    SUMMARIZE (
        Dim_Clusters,
        Dim_Clusters[cluster_nombre],
        Dim_Clusters[n_ofertas],
        Dim_Clusters[salario_mediano_usd],
        Dim_Clusters[rol_dominante]
    )
VAR _MaxN   = MAXX ( _Data, Dim_Clusters[n_ofertas] ) + 0.0001
VAR _MaxSal = MAXX ( _Data, Dim_Clusters[salario_mediano_usd] ) + 0.0001
VAR _Rows =
    CONCATENATEX (
        _Data,
        VAR _Color =
            SWITCH (
                Dim_Clusters[rol_dominante],
                "Data Analyst",       "#FFB020",
                "Data Scientist",     "#00E396",
                "Data Engineer",      "#00D4FF",
                "Analytics Engineer", "#7B2FBE",
                "ML Engineer",        "#FF4D6D",
                "#9090A8"
            )
        VAR _PctN = DIVIDE ( Dim_Clusters[n_ofertas], _MaxN ) * 100
        VAR _PctS = DIVIDE ( Dim_Clusters[salario_mediano_usd], _MaxSal ) * 100
        RETURN
            "<div style='margin-bottom:14px;'>"
                & "<div style='color:" & _Color & ";font-size:13px;font-weight:600;margin-bottom:6px;'>" & Dim_Clusters[cluster_nombre] & "</div>"
                & "<div style='display:flex;align-items:center;margin-bottom:4px;'>"
                    & "<div style='color:#9090A8;font-size:10px;width:60px;'>Ofertas</div>"
                    & "<div style='flex:1;background:#2A2A45;border-radius:3px;height:14px;'>"
                        & "<div style='background:" & _Color & ";width:" & FORMAT ( _PctN, "0" ) & "%;height:100%;border-radius:3px;'></div>"
                    & "</div>"
                    & "<div style='color:" & _Color & ";font-size:11px;width:50px;text-align:right;font-weight:600;'>" & FORMAT ( Dim_Clusters[n_ofertas], "#,##0" ) & "</div>"
                & "</div>"
                & "<div style='display:flex;align-items:center;'>"
                    & "<div style='color:#9090A8;font-size:10px;width:60px;'>Salario</div>"
                    & "<div style='flex:1;background:#2A2A45;border-radius:3px;height:14px;'>"
                        & "<div style='background:#00E396;width:" & FORMAT ( _PctS, "0" ) & "%;height:100%;border-radius:3px;'></div>"
                    & "</div>"
                    & "<div style='color:#00E396;font-size:11px;width:50px;text-align:right;font-weight:600;'>$" & FORMAT ( DIVIDE ( Dim_Clusters[salario_mediano_usd], 1000 ), "0" ) & "K</div>"
                & "</div>"
            & "</div>",
        "",
        Dim_Clusters[n_ofertas], DESC
    )
RETURN
    "<div style='background:#1A1A2E;padding:16px;border-radius:8px;font-family:Segoe UI,Arial,sans-serif;'>"
        & "<div style='color:#9090A8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px;margin-bottom:12px;'>👥 Comparativo de arquetipos</div>"
        & _Rows
    & "</div>"
